### ISSUE TITLE
`SchemaStore` implementation

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#131]
Implementation of a storage layer which handles storing and getting schema.

This may or may not involve new db tables....

**Comment by sandreae** [comment]
I started sketching out db tables and defining the traits for this, then realised that we already have what we need in `DocumentStore` to retrieve and construct `Schema`. The flow would be:

- Fetch a schema's `DocumentView` from the db by it's `DocumentViewId`
- Fetch all the `DocumentView` for all the schema's fields by the same `DocumentViewId`
- Construct a `SchemaView` and `SchemaFieldView`'s from the above
- Construct a `Schema` from the view and fields
- We have a `Schema`, yay! srote it in memory for easy access later

The reverse would be true for storing schema.

With this, we would still have a `SchemaStore` trait, but it would use `DocumentStore` methods underneath. This would be cool as the methods (described above) could be default implementations defined in `p2panda-rs`.

(fun fact: a while ago we decided to split `Schema` into two logs, the schema definition, and the fields separately. This nicely mirrors the current db layout. I only just realised this :rofl:)

**Comment by sandreae** [comment]
Next question....

Are we imagining the `SchemaService`, which keeps schema in memory for easy access, would actually be part of the `SchemaStore`? For example, there could be a kind of caching layer inside `SchemaStore` which stores every requested schema by their id in a hashmap, this would be checked before every `get_schema_by_id()` before hitting the db. Is that wild and dangerous and/or a good idea?

**Comment by cafca** [comment]
Our plan so far was that _all_ schemas are retrieved from the database on startup and every new schema created during runtime is added into the schema service immediately, so there would be no scenario where a call to get a schema from that service needs to hit the db. 

However, now that you put it like that it feels like this could also be a more general caching service that just happens to pre-populate itself with all schemas when it starts up. This sounds very nice but also could be a rabbit hole.

In addition to getting schemas by id we should also have an endpoint to enumerate all registered schemas I think.

**Comment by sandreae** [comment]
> Our plan so far was that all schemas are retrieved from the database on startup and every new schema created during runtime is added into the schema service immediately, so there would be no scenario where a call to get a schema from that service needs to hit the db.

Cool, this is what I understood as well.

> However, now that you put it like that it feels like this could also be a more general caching service that just happens to pre-populate itself with all schemas when it starts up. This sounds very nice but also could be a rabbit hole.

Yeh, that's what I was wondering. Maybe in this case it wouldn't be a massive can of worms, because schemas are refered to by their DocumentViewId, meaning they are immutable. In the case of documents, obvs more problems arrise.

Interesting about the other possible extensions of SchemaStore, I like all those ideas! For now, do you see any issues with not having specialised tables for schema? Still a `SchemaStore`, but under the hood it just hits the `document_view` tables.

**Comment by sandreae** [comment]
I made some progress here. I think for now we don't need to store schema in any concrete place, we can manage without `insert_schema()` because schemas already exist as a collection of document views. Once all of these are present in the db (thank you, materialisation & dependency tasks!) then we can retrieve the schema `get_schema_by_id(I'd: DocumentViewId)` which under the hood gets all schema and schema field definition views, then creates and returns a schema object. It's not the most optimised thing in the world (multiple db calls for each schema) but I don't think that matters for its use case (mostly getting all schema on startup for caching in memory).  A bonus is that the whole `SchemaStore` including `get_all_schema()` can be defined with default implementations leveraging `DocumentStore`, which is rather neat.

**Comment by sandreae** [comment]
Maybe it's misleading / un-necessary that this is a `Store` at all though.... Seeing as it doesn't store anything... We could just pull these methods out and use them when needed in the Schema service? I'm open to suggestions.
