### ISSUE TITLE
Replication based on schema ids

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#138]
We need to tie down our initial replication configuration strategies.

I think the default approach we've been imagining so far is:
- a node can be configured to subscribe to a set of schema ids so that it replicates all logs from known remote nodes that contain documents of any of these schemas

(definition by @cafca in other doc ;-p)

This could be tailored with:
- a node can be configured with a list of public keys whose logs should never be replicated
- a node’s subscription to a schema can be refined so that only logs from a list of specific public keys are replicated

But let's continue the discussion in this issue :+1:

@pietgeursen how does this sound to you? I think it may be a little different from what you had in mind... or??

**Comment by pietgeursen** [comment]
Ok so let's check my understanding:

I see that the entry store has a `get_entries_by_schema` method.

For each entry we'd also need its certificate pool so that it can be verified.

I think `get_entires_by_schema` in the entry store will need some kind of pagination + latest seq mechanism like we do with `get_entries_newer_than_seq`. At the moment is always returns you everything.

**Comment by pietgeursen** [comment]
Also, does this mean that the way I'm developing replication using `get_entries_newer_than_seq` is not useful?

**Comment by pietgeursen** [comment]
Another question assuming you're going to do this "partial replication" using the cert pools:

Do you want to get (and store) the payloads of each entry in the cert pool too? Bamboo doesn't require that.

**Comment by sandreae** [comment]
> Also, does this mean that the way I'm developing replication using get_entries_newer_than_seq is not useful?

Ah, no, this is definitely what we need.

I think configuring what to replicate via schema is a layer before the actual entries get transported, the same as configuring replication by who published the data (public key follows), but instead following schema. We want different nodes to be able to configure which logs they replicate by the schema of the data they contain. So we will still be saying `get_entries_newer_than_seq` for a certain log.

 > I see that the entry store has a get_entries_by_schema method.

I don't think this method is so related to replication, it's more for us internally to collect all entries which were published under a certain schema (regardless of author).

**Comment by pietgeursen** [comment]
So for my replication work right now, is it ok that we just do public key follows? (the public keys + log Ids are in config)

Later we can add which schema you want to replicate and we can build something to go from schema to public keys + log ids?

Or am I still not understanding? :)

**Comment by sandreae** [comment]
Yeh, I imagine the mechanisms will be the same. Not sure if there are some important subtle differences though....

**Comment by sandreae** [comment]
In the simplest implementation of a "follow schema" replication method we literally don't care about public keys at all, we want all logs connected to that schema.

**Comment by sandreae** [comment]
> Do you want to get (and store) the payloads of each entry in the cert pool too? Bamboo doesn't require that.

We don't need that for the cert pool :+1:

**Comment by sandreae** [comment]
> Or am I still not understanding? :)

If there's any miss-understand I'm _sure_ it's because of my inability to write words which make sense :rofl:

**Comment by adzialocha** [comment]
:wave: 

All of this sounds good to me :+1:

> So for my replication work right now, is it ok that we just do public key follows? (the public keys + log Ids are in config)
> Later we can add which schema you want to replicate and we can build something to go from schema to public keys + log ids?
> Or am I still not understanding? :)

p2panda is more schema- than public key centric. Maybe thats a difference to ssb where nodes represent "single authors" while p2panda is more of an application-data network where nodes can support one to many applications of many authors. We definitely would like nodes to replicate data based on schema ids at _some_ point.

For the timeplan though it does not really matter, as long as we can have _some_ replication mechanism going until the next NGI period (30.06.). Also I can see that what you're implementing @pietgeursen already holds quite some complexity - it really makes sense to take it step by step.

We would be totally fine with a first replication mechanism going by a list of public keys in the config and then move over to schema ids in the next step.

As @sandreae already said, it could be almost seen as a layer on top of your work so I don't think you're doing something which will be not useful later on. Roughly I would see the replication mechanism like that:

```
1. Node 1 asks another node 2 if it has new entries for the schemas A, B, C and D
2. Node 2 replies with a list of entries with public keys, log ids and last seq numbers it knows about for the schemas it supports (all or a subset of A, B, C and D)
3. Node 1 calculates the delta and requests all entries of these public keys and log ids mentioned by Node 2 it doesn't have yet, validates and stores them
```

Without going too much into the details of the replication protocol + Rust methods (I assume there are different ways to already send some more information in some requests etc.) I assume that point 1. is the future we want and point 2. and 3. is roughly what you're currently implementing?

> Another question assuming we're going to do this "partial replication" using the cert pools:
> Do you want to get (and store) the payloads of each entry in the cert pool too? Bamboo doesn't require that.

We thought we tackle "partial replication" later on, for now its super fine to "naively" download all payloads for each entry :+1:

**Comment by sandreae** [comment]
:pray: thanks for the clear summary ;-p

**Comment by pietgeursen** [comment]
Thanks for the summary @adzialocha. I didn't get how we'd do the schema based replication and this is a great path forward.

> 1. Node 1 asks another node 2 if it has new entries for the schemas A, B, C and D
> 2. Node 2 replies with a list of entries with public keys, log ids and last seq numbers it knows about for the schemas it supports (all or a subset of A, B, C and D)
> 3. Node 1 calculates the delta and requests all entries of these public keys and log ids mentioned by Node 2 it doesn't have yet, validates and stores them

>  I assume that point 1. is the future we want and point 2. and 3. is roughly what you're currently implementing?

I'm really only implementing 3. Node 1 needs to have prior knowledge of the authors + log ids it wants to replicate from Node 2.

> Node 1 asks Node 2 if it has new entries for the schemas A, B, C and D

Just double checking: This isn't implemented in the db layer yet eh? I was looking around but can't see anything but I might be missing something.

How would you ask for "new" schema entries out of interest? What do you use as a "cursor" to represent your current state?

**Comment by pietgeursen** [comment]
Thanks for the summary @adzialocha. I didn't get how we'd do the schema based replication and this is a great path forward.

> 1. Node 1 asks another node 2 if it has new entries for the schemas A, B, C and D
> 2. Node 2 replies with a list of entries with public keys, log ids and last seq numbers it knows about for the schemas it supports (all or a subset of A, B, C and D)
> 3. Node 1 calculates the delta and requests all entries of these public keys and log ids mentioned by Node 2 it doesn't have yet, validates and stores them

>  I assume that point 1. is the future we want and point 2. and 3. is roughly what you're currently implementing?

I'm really only implementing 3. Node 1 needs to have prior knowledge of the authors + log ids it wants to replicate from Node 2.

> Node 1 asks Node 2 if it has new entries for the schemas A, B, C and D

Just double checking: This isn't implemented in the db layer yet eh? I was looking around but can't see anything but I might be missing something.

How would you ask for "new" schema entries out of interest? What do you use as a "cursor" to represent your current state?

**Comment by sandreae** [comment]
Glad this makes sense, sorry about any earlier confusion :cry: 

> Just double checking: This isn't implemented in the db layer yet eh? I see there's [get_entries_by_schema](https://github.com/p2panda/aquadoggo/blob/ec4db29e123bedbad17c392fd773bae3c6f57043/aquadoggo/src/db/stores/entry.rs#L292) but it gives you all of them. How would you ask for "new" schema entries out of interest? What do you use as a "cursor" to represent your current state?

No, we don't have this implemented yet. We have `get_all_schema` and `get_schema_by_id` in `SchemaStore`, which might be used in this flow, but they return the actual schema rather than any information about the state of related logs.

Schema's are identified by a hash id, and all logs know about which schema they are concerned with. We will need something like `get_log_seq_for_schema(schema_id: SchemaId) ->  Vec<(Author, Vec<(LogId, SeqNum)>>` I suppose.

**Comment by adzialocha** [comment]
I'm closing this in favor of https://github.com/p2panda/handbook/issues/203 as we need to specify things first ✌️
