### ISSUE TITLE
Sending empty string as GraphQL argument in `publishEntry` mutation crashes node

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#157]
Sending the following request fails and crashes the thread with the following error:

**Error:**

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: DecodeInputIsLengthZero', /home/adz/.cargo/git/checkouts/p2panda-fb44b351afe3c13e/2fba9c7/p2panda-rs/src/entry/entry_signed.rs:119:59
```

**Mutation:**

```graphql
mutation TestPublishEntry($entryEncoded: String!, $operationEncoded: String!) {
  publishEntry(entryEncoded: $entryEncoded, operationEncoded: $operationEncoded) {
    logId,
    seqNum,
    backlink,
    skiplink,
  }
}
```

**Variables:**

```json
{
  "entryEncoded": "",
  "operationEncoded": ""
}
```

**Comment by sandreae** [comment]
I just looked at this, granted quite briefly, but it looks a bit strange.

Here the encoded entry and operation are being constructed from their passed strings and the results unwrapped: https://github.com/p2panda/aquadoggo/blob/72df98be3cf4723a44ae824fbff9aa0283067f19/aquadoggo/src/graphql/client/mutation.rs#L36-L40

But it doesn't seem to be causing the method to return an error when empty strings are passed... ?

**Comment by adzialocha** [comment]
> But it doesn't seem to be causing the method to return an error when empty strings are passed... ?

The error misses a stack trace, but I think it got already unwrapped much earlier. Probably within the `bamboo` crate.

**Comment by adzialocha** [comment]
Indeed, its here: https://github.com/pietgeursen/bamboo-rs/blob/ee8cf5fbfded69ef9c4f9457e85643f23bcc2257/bamboo-rs-core/src/entry/decode/mod.rs#L18

**Comment by adzialocha** [comment]
Interesting, I guess we're using this conversion method here to decode the entry:

https://github.com/pietgeursen/bamboo-rs/blob/ee8cf5fbfded69ef9c4f9457e85643f23bcc2257/bamboo-rs-core/src/entry/mod.rs#L75-L81

Via .. https://github.com/p2panda/p2panda/blob/main/p2panda-rs/src/entry/decode.rs#L27-L28

But its using `into()` and not `try_into()`?

**Comment by sandreae** [comment]
Ah, so we need better validation in the `EntrySigned` constructor.

**Comment by sandreae** [comment]
I would expect this to be true `assert!(EntrySigned::new("").is_err());`

**Comment by sandreae** [comment]
It's amazing this never came up before :rofl:

**Comment by adzialocha** [comment]
> It's amazing this never came up before rofl

We rarely test invalid cases haha

**Comment by adzialocha** [comment]
Especially when data is being deserialized via serde, this is where the wild universe lives :-D

**Comment by sandreae** [comment]
Lolz, true.

**Comment by sandreae** [comment]
https://github.com/p2panda/p2panda/blob/61ed86202af75f85abc1d655291c93397528e40a/p2panda-rs/src/entry/entry_signed.rs#L179-L183

**Comment by sandreae** [comment]
Just checks the hex encoding, not if it's a valid bamboo entry.

**Comment by adzialocha** [comment]
This is a related ticket: https://github.com/p2panda/p2panda/issues/35
