### ISSUE TITLE
Improve error handling when sending a duplicate entry via GraphQL `publishEntry` 

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#159]
Currently it returns a "DUPLICATE" error coming directly from SQL which makes sense, but I expect the invalid entry to be catched _before_ it hits the database (by checking the log integrity for example).

**Comment by cafca** [comment]
The error coming from the db is not necessarily a bad thing I think. We don't want to hit the db another time just to check something that a unique index can also catch. But returning a nice and friendly error message that doesn't depend would of course be nice.

**Comment by adzialocha** [comment]
> The error coming from the db is not necessarily a bad thing I think. We don't want to hit the db another time just to check something that a unique index can also catch. But returning a nice and friendly error message that doesn't depend would of course be nice.

I agree with thos being a totally fine pattern 👍

Still I wonder, shouldn't have the bamboo log integrity validation thrown before?

**Comment by adzialocha** [comment]
> The error coming from the db is not necessarily a bad thing I think. We don't want to hit the db another time just to check something that a unique index can also catch. But returning a nice and friendly error message that doesn't depend would of course be nice.

I agree, this is a totally fine pattern! 👍

Still I wonder, shouldn't the bamboo integrity validation throw before? Of course, two identical entries are calid, but if one already exists, the seq num and backlink is wrong?

**Comment by sandreae** [comment]
> Of course, two identical entries are valid if they are not appended yet, but if one already exists, the seq num and backlink is wrong?

I haven't checked this myself, so this may be wrong, but is it because we are seeing this always with the first entry in a log? Then I could imagine the first error we hit is "DUPLICATE" for the log id.

**Comment by sandreae** [comment]
Looking at the verification code, we could probably catch this case here:

https://github.com/p2panda/p2panda/blob/fa7d916dfaee356a97d8e833174dfd8ba8aac9aa/p2panda-rs/src/storage_provider/traits/storage_provider.rs#L150-L162

**Comment by sandreae** [comment]
I think `find_document_log_id()` is a bit too smart, it returns either the log_id for the passed document_id, _or_ the next available log id if there is no existing document. So we don't know if it's a new or existing log which is coming back.

We want to do: `if existing_log_id & operation.is_create() { "Ouch!" }`
