### ISSUE TITLE
Re-schedule unmaterialized operations during startup

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#162]
There is a chance that operations stay unmaterialized when the node shuts down after storing them in the database and before the worker could take care of them. For this we need to keep some state which remembers which operations have been "completed" and which are still "pending".

We could add a column for every operation in the database with a "dirty" flag. It gets set to "true" after materialization. When the node starts up it goes through the database and dispatches a `reduce` task for every operation which is still "false".

**Comment by adzialocha** [comment]
Or could we find that out with our current structure? Make a query which finds operations which are not mentioned by and document view?

**Comment by adzialocha** [comment]
Pinging database guru @sandreae 👨‍🏫

**Comment by sandreae** [comment]
Interesting problem!

> Make a query which finds operations which are not mentioned by and document view?

We could for sure make this query, but I don't think it would solve this problem. There will be many operations in the db which aren't part of a document view as they were never materialised in a view, but they are just part of the document graph. So this query would return way too many operations, most of which we don't want to reduce again.

> We could add a column for every operation in the database with a "dirty" flag. It gets set to "true" after materialization. When the node starts up it goes through the database and dispatches a reduce task for every operation which is still "false".

This makes sense to me though! Another similar approach would be to have a dedicated table for each class of task, where operation ids would be stored. Rows are inserted when an operation is sent to the bus, and removed after the task completes. So if there are any entries in the table, we know a task didn't complete and we re-run. Could have the same pattern for dependency tasks too (i think we have the same problem there too, right?)

**Comment by adzialocha** [comment]
> We could for sure make this query, but I don't think it would solve this problem. There will be many operations in the db which aren't part of a document view as they were never materialised in a view, but they are just part of the document graph. So this query would return way too many operations, most of which we don't want to reduce again.

Right, that makes totally sense, thanks!

> Another similar approach would be to have a dedicated table for each class of task, where operation ids would be stored. Rows are inserted when an operation is sent to the bus, and removed after the task completes. So if there are any entries in the table, we know a task didn't complete and we re-run.

I'm also wondering if a dedicated "system" table would be better, as I don't really see why operations need to know about the materialization state (I love that they have this "immutable" aura around them).

> Could have the same pattern for dependency tasks too (i think we have the same problem there too, right?)

The dependency task is _always_ triggered by the reduce task, so I think it will be enough to keep it simple like that, even if it causes some redundancy (the tasks are not very expensive). Of course, later we might need to keep track of more things as some tasks might not be triggered by reduce anymore, but thats more far away.

**Comment by sandreae** [comment]
>  don't really see why operations need to know about the materialization state (I love that they have this "immutable" aura around them).

Yeh, I totally agree, seems a little odd that they suddenly have a "was I materialised" flag which they don't themselves really care about.

> The dependency task is always triggered by the reduce task.

Ah, true. But if a reduce task completes, dispatches a dependency task, and then the node crashes before it is started? Wouldn't we need to restart that dependency task? (the reduce task would be correctly flagged as completed, but we wouldn't have processed it's dependencies yet)

**Comment by adzialocha** [comment]
> Ah, true. But if a reduce task completes, dispatches a dependency task, and then the node crashes before it is started? Wouldn't we need to restart that dependency task? (the reduce task would be correctly flagged as completed, but we wouldn't have processed it's dependencies yet)

Oh, I haven't thought about this, good point ..

**Comment by adzialocha** [comment]
This definitely is not a p2panda storage trait, but we can still have one inside aquadoggo, the abstractions are really good.
