### ISSUE TITLE
Worker crashes on materialization of pinned relation field

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#191]
The node fails with materializing a pinned relation field.

**Steps to reproduce:**

1. Use https://github.com/p2panda/send-to-node (`monday-hagggs` branch, wiped database)

2. Run the following commands:

    ```bash
    # Create schema A
    cat 001-schema-field-definition-name.toml | cargo run -- -k ./key-bug.txt
    cat 002-schema-definition-venue.toml | cargo run -- -k ./key-bug.txt

    # Create schema B
    cat 009-schema-field-definition-venue.toml | cargo run -- -k ./key-bug.txt
    cat 010-schema-definition-event.toml | cargo run -- -k ./key-bug.txt
    ```
    
The node crashes with following error (`invalid field type`):

```
[2022-07-05T11:48:14Z ERROR aquadoggo::materializer::worker] Critical error in worker schema with task QueueItem { id: 3, input: TaskInput { document_id: None, document_view_id: Some(DocumentViewId([OperationId(Hash("002037aff245c9c12927250e2e2b075ba94cc23def6e1360ff78c790adb748e888db"))])) } }: invalid field type
```

**Comment by sandreae** [comment]
I believe this is solved here: https://github.com/p2panda/aquadoggo/pull/192

**Comment by sandreae** [comment]
@adzialocha could you try the above PR out with your database from last night (if you still have it). I run through the steps send-to-node and it seems fine, except I seem to be missing one schema field, but I get this nice response now:

```
{
  "data": {
    "schema_definition_v1": [
      {
        "viewId": "00203a3f68d2a1d4a42d37e1e025d93063997e3cdbb5cfb56e33abd4dc1733776b37",
        "documentId": "00203a3f68d2a1d4a42d37e1e025d93063997e3cdbb5cfb56e33abd4dc1733776b37",
        "name": "venue",
        "description": "Fantastic festival venues",
        "fields": [
          {
            "viewId": "002007c35a265ffaaca41cca33f385798d9698769e25b82dd79211bc8583a765d8b9",
            "documentId": "002007c35a265ffaaca41cca33f385798d9698769e25b82dd79211bc8583a765d8b9",
            "name": "name",
            "type": "str"
          }
        ]
      },
      {
        "viewId": "0020a654068b26617ebd6574b1b03853193ccab2295a983bc85a5891793422832655",
        "documentId": "0020a654068b26617ebd6574b1b03853193ccab2295a983bc85a5891793422832655",
        "name": "chat_message",
        "description": "Send messages.",
        "fields": [
          {
            "viewId": "0020e486729825b09fc0fba106e834700c45aff774f3cbf132a2514aaa36a3cc34fc",
            "documentId": "0020e486729825b09fc0fba106e834700c45aff774f3cbf132a2514aaa36a3cc34fc",
            "name": "message",
            "type": "str"
          }
        ]
      },
      {
        "viewId": "0020bdaf8b8f64bf9abfcb1c6ad8e21b6f96f032facfd220ae63fb1a788cf7bee35b",
        "documentId": "0020bdaf8b8f64bf9abfcb1c6ad8e21b6f96f032facfd220ae63fb1a788cf7bee35b",
        "name": "event",
        "description": "An event in a historical venue",
        "fields": [
          "not found",
          {
            "viewId": "002007c35a265ffaaca41cca33f385798d9698769e25b82dd79211bc8583a765d8b9",
            "documentId": "002007c35a265ffaaca41cca33f385798d9698769e25b82dd79211bc8583a765d8b9",
            "name": "name",
            "type": "str"
          }
        ]
      }
    ]
  }
}
```

**Comment by adzialocha** [comment]
> I believe this is solved here: #192

Isn't that another issue? This fixes that a missing field does not break building the schema (or it will not be built at all). But the error (which I haven't attempted reproducing yet), seemed to have happend before that (inside the materializer).

**Comment by sandreae** [comment]
Hmm, not sure, I think the crashing we were experiencing last night was because of this, but if this issue is about something else then yes this fix is maybe not related :+1:

**Comment by adzialocha** [comment]
> Hmm, not sure, I think the crashing we were experiencing last night was because of this, but if this issue is about something else then yes this fix is maybe not related :+1: 
> 

Yeah I think this is something else happening before, causing corrupt data which showed another bug. Think you refer to this: https://github.com/p2panda/aquadoggo/issues/188

**Comment by adzialocha** [comment]
Aha! So I think the problem is somewhere around our (cool) representation of relations: `pinned_relation(<schema_id)` and how it is parsed maybe?

The error comes from here:

https://github.com/p2panda/p2panda/blob/879910a237780e407cb0795c7be59ec63759e97d/p2panda-rs/src/schema/field_types.rs#L119

.. when I change the `010-schema-definition-event.toml` operation field type to:

```
[fields.type]
type = "str"
value = "pinned_relation(venue_002020da00fe6fb680537b4f46858ca5e9ceb45983401cdad8abf1477330c9ce9fdc)"
```

I receive a "not found" then for the schema field when I do a GraphQL query ..

**Comment by adzialocha** [comment]
Closing this now and I guess we move on with this issue: https://github.com/p2panda/p2panda/issues/388
