### ISSUE TITLE
Mistake in logic for calculating skiplink in get_entry_args

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#20]
After some brain bending in the chat me and @cafca think there may be an error in the logic calculating the skiplink for the return value in get_entry_args here:

https://github.com/p2panda/aquadoggo/blob/9cfa430e65cfb034bc9cbf30be442758d281ba55/aquadoggo/src/rpc/api.rs#L133

We suggest it should be something more like this:

`&entry_backlink.next_seq_num.skiplink_seq_num().unwrap()`

So that the returned value is the skiplink for the entry we are about to create (instead of for the backlink/latest_entry).

**Comment by sandreae** [comment]
Great!

**Comment by adzialocha** [comment]
Yes, this sounds more right! :sun_with_face:
