### ISSUE TITLE
Add document store methods that return `Document` instead of `DocumentView`

### ISSUE THREAD

**Issue by cafca** [p2panda/aquadoggo#203]
The document store methods currently return `DocumentView` only, which doesn't contain metadata (schema, author, etc.). Instead I think we should always include metadata in these store methods. Currently, `Document` always contains the full list of operations, which of course would make this change a bit expensive. However, this list of operations is currently only used in testing of the document module to verify the correct order of operations after reduction.

Proposal:

- let `get_document_by_id` return a `Document`
- replace `get_document_view_by_id` with `get_document_by_view_id` and let it return a `Document` with the specified view inside.
- let `get_documents_by_schema` return `Vec<Document>`
- make `operations` on `DocumentMeta` an `Option` with only module-level visibility to be used for testing.

**Comment by sandreae** [comment]
Hey! I think this may well be a very good idea, but as I said elsewhere, I just want to be clear why/where we need this to make sure we make changes in the right place. Especially cos it seems we can do everything we need _right now_.

Of course, for getting more tasty stuff into the GraphQL responses, we need exactly this access to the metadata, but also we imagine having custom queries especially for this purpose, eventually not using the existing storage provider methods. 

Maybe a nice and easy path forward is to just to add the methods you would like straight onto `SqlStorage` (without replacing the existing ones) then we can use them and see how much better our lives become :rofl: :star:

**Comment by cafca** [comment]
Yes, we can do that. More methods, more possibilities! This approach could become hard to maintain eventually, though. 

I think we should still rename the existing methods because their names don't match what they do.

**Comment by sandreae** [comment]
Yeh, wasn't really meaning we would keep it like that forever, more as a transitional thing and to make sure it's the behaviour we want.

Could you add the changes you want to make to this tracking issue: https://github.com/p2panda/aquadoggo/issues/149?
