### ISSUE TITLE
Separate client and replication API

### ISSUE THREAD

**Issue by cafca** [p2panda/aquadoggo#223]
Having looked at it a lot in the past weeks the combined replication and client api didn't feel that nice after all. I think it would be friendlier to separate these two apis.

What do you think about separating these so we have two actual endpoints:

- host:2020/graphql <-- client api
- host:2020/replication <-- replication api

**Comment by adzialocha** [comment]
Oh I like that! Better than different ports 👍

**Comment by sandreae** [comment]
Nice :+1:

**Comment by adzialocha** [comment]
We're not sure anymore about this, lets think about it more!
