### ISSUE TITLE
GraphQL Docs look funny with `Scalar` suffixes

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#229]
![Screenshot 2022-08-11 at 12-01-58 Playground - http __localhost 2020_graphql](https://user-images.githubusercontent.com/1822473/184113530-e0034112-c0a0-4286-abe7-eebe371e7c19.png)

Is there a way to tell `async-graphql` that we want a different name for the scalar? It looks like it currently derives it from the struct names.

**Comment by cafca** [comment]
I think I just found an undocument macro argument for that!
