### ISSUE TITLE
Validating relation fields of published operations

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#250]
Reject operations which arrive via the client api which contain a relation to a document/schema which doesn't exist on this node.

Cases where this might occur are:

- operation following an application schema with a relation to a non-existent document
- operation following the `schema_field_definition_v1` schema containing a relation type claiming a non-existent schema
- operation following the `schema_definition_v1` schema containing a field relation which doesn't exist

**Comment by sandreae** [comment]
Do we want this to be part of our specification? Currently I would say it is more a concern of how strict we would want `aquadoggo` to be regarding what it considers to be valid application data. It's a valid concern though, and could be added to the spec if we think it will be important in all cases.

**Comment by adzialocha** [comment]
Some ideas:


> operation following an application schema with a relation to a non-existent document

That's probably okay behaviour, as our system is designed to understand to not have all information ready (having the worker queue in mind). Currently you would receive a `null` value for the relation and that's cool.

> operation following the schema_field_definition_v1 schema containing a relation type claiming a non-existent schema

That's not so nice, all dependencies should be given before registering a schema. Though, I'm also happy if this is just handled during materialization (the schema just doesn't get materialized), not on API level. This is already then implemented, right?

> operation following the schema_definition_v1 schema containing a field relation which doesn't exist

Same as above.

**Comment by adzialocha** [comment]
Generally speaking: I'm happy with these things failing "silently". Thats maybe not suuuper user friendly (you might wonder why something did not work out and start comparing hashes), but with some nice tooling (aka fishyfish) one day, hopefully that process of creating schemas and avoiding common pitfalls will also be guided.

**Comment by adzialocha** [comment]
Then you still have the option to create schemas out-of-order and if you simply lack some info they shouldn't be created at all. My guess is that we already implemented it like that?

**Comment by sandreae** [comment]
Ok, great, thanks for your feedback 👍

**Comment by sandreae** [comment]
> My guess is that we already implemented it like that?

Yes this is our current design.

**Comment by sandreae** [comment]
We don't want our public API to enforce these rules as our materialisation logic accounts for documents of all kinds existing with related documents missing (application docs are still materialised, schema are not) and we want to allow for messages arriving out of order.

In that case there is nothing to implement and I'm closing this issue.
