### ISSUE TITLE
When materialization takes long time "View not found" error when querying document

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#254]
Querying a document (which exists) by `documentId` sometimes returns this error:

```json
{
  "response": {
    "data": null,
    "errors": [
      {
        "message": "View not found"
      }
    ],
    "status": 200,
    "headers": {
      "map": {
        "content-length": "53",
        "content-type": "application/json"
      }
    }
  },
  "request": {
    "query": "\n    query FetchBoard($documentId: String!) {\n      board: zoo_adventures_00209403784eea2ba5236f9083472f040a90babf4df1b64efbbaae58eb51aa67fd4d(id: $documentId) {\n        meta {\n          viewId\n        }\n        fields {\n          game_field_1 game_field_2 game_field_3 game_field_4 game_field_5 game_field_6 game_field_7 game_field_8 game_field_9 game_field_10 game_field_11 game_field_12 game_field_13 game_field_14 game_field_15 game_field_16\n        }\n      }\n    }\n  ",
    "variables": {
      "documentId": "0020c301d6595e12cbd472d21ac4c1bdfde02ec4e8d7ea299f723130d64eb65e500d"
    }
  }
}
```

The error comes from this line: https://github.com/p2panda/aquadoggo/blob/main/aquadoggo/src/graphql/client/utils.rs#L22

It often happens right after when the document gets updated. Maybe it gets temporarily deleted in the database before the new materialized version gets inserted? The document has a fairly large operation graph ..

**Comment by adzialocha** [comment]
Okay, probably this is a "normal" condition when materialization takes long time:

The latest view id is not materialized yet, the client knows about it already though and inserts it in the query. When checking if the requested view id matches the claimed schema, it fails.

**Comment by sandreae** [comment]
> Maybe it gets temporarily deleted in the database before the new materialized version gets inserted?

We aren't deleting views in the db at the moment, so I don't think it's this.

I suspect it is happening as the `document` table is updated first, then the view inserted to `document_views` table (if the document isn't deleted). So if we queried the document (or in this case the documents schema) by view id in this moment then we wouldn't find anything. Like this this:

A1) `document` table updated with new view id (the isn't inserted yet)
B1) query the document for it's newest view
B2) query the `document_views` table for the retrieved view -> Error!
A2) insert the new view to the `document_views` table

We can fix this by adding a `transaction` around these two sql queries :+1:

Side thought, it makes me wonder if we need to think about best practice for how we query documents/views, maybe getting the document id and querying that is the most reliable way, seeing as views may be deleted.

**Comment by adzialocha** [comment]
> We can fix this by adding a `transaction` around these two sql queries :+1:

Super! Sounds good. Everything which needs multiple writes before it's considered a "final" state should be wrapped into one transaction, maybe we find more of these in other places?

**Comment by sandreae** [comment]
> maybe we find more of these in other places?

Yes, maybe!
