### ISSUE TITLE
Use or remove custom result type

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#273]
We define a custom result type in `errors.rs` but we never use it. We should either use it or remove it.

**Comment by adzialocha** [comment]
Yeah, good point! Think its already came up here: https://github.com/p2panda/aquadoggo/issues/56 - let's remove it, as on something that high level as aquadoggo we will never care about error types 👍🏻

**Comment by sandreae** [comment]
Done: https://github.com/p2panda/aquadoggo/commit/6815cf44baa78b67b8482236e21654abda39eaa4
