### ISSUE TITLE
libp2p deprecation warnings, suggests `Keypair::into_ed25519`

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#295]
This makes `clippy` currently sad 😿 :

```
warning: use of deprecated tuple variant `libp2p::libp2p_identity::Keypair::Ed25519`: This enum will be made opaque in the future, use `Keypair::into_ed25519` instead.
  --> aquadoggo/src/network/identity.rs:50:22
   |
50 |             Keypair::Ed25519(key_pair) => key_pair.secret(),
   |                      ^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated tuple variant `libp2p::libp2p_identity::Keypair::Ed25519`: This enum will be made opaque in the future, use `Keypair::into_ed25519` instead.
  --> aquadoggo/src/network/identity.rs:82:33
   |
82 |         let key_pair = Keypair::Ed25519(private_key.into());
   |                                 ^^^^^^^

warning: use of deprecated field `libp2p::libp2p_identity::Keypair::Ed25519::0`: This enum will be made opaque in the future, use `Keypair::into_ed25519` instead.
  --> aquadoggo/src/network/identity.rs:50:30
   |
50 |             Keypair::Ed25519(key_pair) => key_pair.secret(),
   |                              ^^^^^^^^
```

**Comment by mycognosist** [comment]
Thanks for flagging this! I'm on it.

**Comment by mycognosist** [comment]
The changes to the API are quite painful. I have a working solution but it requires inefficient type transformations. I'll wait a little bit until the changes from this PR are released: https://github.com/libp2p/rust-libp2p/pull/3626/files

**Comment by adzialocha** [comment]
> The changes to the API are quite painful. I have a working solution but it requires inefficient type transformations. I'll wait a little bit until the changes from this PR are released: https://github.com/libp2p/rust-libp2p/pull/3626/files

Oh yes, this looks ugly. We could add attributes to ignore these warnings and add a comment to linking to this issue?

**Comment by adzialocha** [comment]
> > Oh yes, this looks ugly. We could add attributes to ignore these warnings and add a comment to linking to this issue?
> 
> That's a good idea. Do you know how to silence these warnings? `#[allow(clippy::deprecated)]` is not having the desired effect for me.

How is `#[allow(deprecated)]` (without the `clippy` part?)

**Comment by mycognosist** [comment]
Ah! That's the one. Thanks :)
