### ISSUE TITLE
Simplify network CLI options and configuration

### ISSUE THREAD

**Issue by mycognosist** [p2panda/aquadoggo#319]
Related to https://github.com/p2panda/aquadoggo/issues/313

The CLI and configuration related to `aquadoggo` networking can be greatly simplified:

- Combine `--rendezvous-address` and `--rendezvous-peer-id` into a single option by incorporating the peer ID into the multiaddr
  - E.g. `--rendezvous-address /ip4/198.51.100.0/udp/2022/quic-v1/p2p/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N`
- Remove the `--rendezvous-client true` option
  - If `--rendezvous-address <multiaddr>` is provided, we assume rendezvous client mode

The same can be applied to relay options.

This means we can reduce the following subset of 8 CLI flags:

`--rendezvous-address`
`--rendezvous-peer-id`
`--rendezvous-server`
`--rendezvous-client`
`--relay-address`
`--relay-peer-id`
`--relay-server`
`--relay-client`

To these 4 options:

`--rendezvous-address`
`--rendezvous-server`
`--relay-address`
`--relay-server`

-----

In some future change, I can imagine the rendezvous and relay servers being on by default. Then the `--rendezvous-address` and `--relay-address` options could be combined into a single option:

`--bootstrap-nodes /ip4/198.51.100.0/udp/2022/quic-v1/p2p/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N /ip4/152.11.132.7/udp/2022/quic-v1/p2p/12D3KooWAA7uPB3qGYxkhkcSfZD63biANQehJXKWW2mEUndgSbrW`

Or, even better, we could just use the existing `--remote-peers` option for this purpose.

**Comment by adzialocha** [comment]
I was wondering about one thing, if I wouldn't know _at all_ what all of this is about I might wonder what the difference between an `address` and a `server` is by just looking at the names of these arguments.

*"So, I want to connect to a rendezvouz server, do I have to put the address under address or under server?"*

I assume that the server arguments are all flags to turn on the server functionality, right? The pattern `--rendezvous-server true` is slightly verbose, especially when the opposite option is already the default you will likely never need to write `--rendezvous-server false`.

So with these two things in mind, how about that:

`--rendezvous-address`
`--relay-address`
`--enable-rendezvous-server`
`--enable-relay-server`

.. while the `enable` flags are simply just flags, which can't be turned `true` or `false`. By setting that flag it is automatically truthy.

**Comment by mycognosist** [comment]
Great, I like it! I think your suggestion makes the usage clearer.
