### ISSUE TITLE
Documents not materializing when entries sent via replication

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#390]
It seems that all entries are now making it across during replication correctly, but I'm not seeing the documents being materialized. It could be something to do with them arriving too quickly, but I'm not sure. More investigation needed!

**Comment by adzialocha** [comment]
Maybe my quick refactoring of the materializer service changed something? Maybe the service message doesn't get picked up anymore. Did you add some logging there?

**Comment by sandreae** [comment]
I think this behaviour might actually be caused by https://github.com/p2panda/aquadoggo/issues/391 as all entries are not arriving at the remote peer. 

Will keep this open until that issue is sorted though incase.

**Comment by sandreae** [comment]
The entries were not actually being sent, so I don't think the issue was here.
