### ISSUE TITLE
Double insertion of same view into `document_views` table during materialization

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#398]
In the situation where the materializer task queue contains both:
- a `dependency` task for a document containing a relation to document `a` at view `3915a` 
- a `reduce` task for document `a` which resolves to view `3915a`

Then as both of these tasks are resolving and storing a view into the store then there will be a critical error:

```
Critical error in worker reduce with task <QueueItem 1 w. <TaskInput 00209f6b09271e1a71ae118d1db23247e3f9365a067d05a7c600f6294efe2853915a/->>: A fatal error occured in DocumentStore: error returned from database: (code: 1555) UNIQUE constraint failed: document_views.document_view_id
```

**Comment by adzialocha** [comment]
The task manager deduplicates only within workers but not across them, this needs probably changing, I'll think about it a bit more but can't see any issues yet.

**Comment by sandreae** [comment]
Temp fix: https://github.com/p2panda/aquadoggo/pull/387/files#diff-641af54a1fa4a1a4ab70451a0d3ae17354778caf603b3e20095101be68e45db7R462

**Comment by adzialocha** [comment]
Related discussion: https://github.com/p2panda/aquadoggo/pull/387#discussion_r1212334388

**Comment by sandreae** [comment]
Note: if we're happy to allow this double insertion, should it be solved in the SQL or in code?
