### ISSUE TITLE
Ignore duplicate data arriving at the ingest

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#433]
An ingest error can occur on inserting an entry + operation into the store if concurrent replication sessions are handling the same (or overlapping) target sets. This is expected behaviour and shouldn't shut down the replication session with the connected peer. Currently all errors occurring during replication are treated the same, maybe ingest errors should be logged but not elevated into a critical replication error.

**Comment by sandreae** [comment]
Good overview of the issue, thanks for taking a look.

> We reflect upon our validation structure and see how we can both account for a) invalid data and according reaction to that b) duplicate data.

This would be a good solution. If we implement it in `aquadoggo` then it would involve some duplicate decoding of entries, which isn't terrible. But we could also maybe add it to the validation flow within `publish` and return a suitable error which we then catch in `aquadoggo`.

> The issue we're facing with this I think is that we allowed duplicate connections in our system now (with using libp2p) and we changed our thinking in the sync manager to account for that, now the issue grown further down to the validation layer. 

I'm not sure this is the case. Even with only one connection per peer, we can still find the same entry arriving from different peers at the same time.

**Comment by adzialocha** [comment]
Ja cool! Just detecting duplicates and ignoring these particular errors sounds like a good solution to me.
