### ISSUE TITLE
Do not show multi addresses to users when displaying INFO-level logs

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#509]
They are an internal libp2p detail and we don't need to communicate them to the users of aquadoggo

**Comment by sandreae** [comment]
Maybe we can get this done before the release if it isn't already.

**Comment by adzialocha** [comment]
> Maybe we can get this done before the release if it isn't already.

Yes, that's nice! In the config PR I already prepared a function which translated multiaddr to regular `SocketAddr` representation.

**Comment by adzialocha** [comment]
https://github.com/p2panda/aquadoggo/commit/466869858268f79ed73ba24ce03ca0505a2d7cf8
