### ISSUE TITLE
Use `anyhow` macro instead of custom Error types

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#56]
We don't really need custom error types for aquadoggo?

**Comment by adzialocha** [comment]
lol, nothing in this file is actually used, I just removed it in https://github.com/p2panda/aquadoggo/commit/78f7885afeea029451dd4333fb8e7313d239b156

**Comment by sandreae** [comment]
Haha, that's obviously cos we don't do errors.
