### ISSUE TITLE
Materialised blobs sometimes corrupted / missing bytes

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#586]
Sometimes blobs are materialised with missing bytes. Noticed mostly when uploading larger files.

**Comment by sandreae** [comment]
I wonder if it's connected to https://github.com/p2panda/aquadoggo/issues as we use the pagination API to retrieve blob pieces.

**Comment by adzialocha** [comment]
Hmn, looking at the pictures I doubt that, the data is there, its just corrupted? If it would be the pagination issues we would have whole parts missing?

**Comment by sandreae** [comment]
Not sure about the images, but I've observed materialised blobs (uploaded successfully using `send-to-node`) having a smaller file size (roughly 40mb upload losing a couple of mb). I assume because it's missing pieces. I'll try and write a test for this though to support the theory.

**Comment by adzialocha** [comment]
Yeah, with large blobs it's possible as pagination will play a role then.

**Comment by sandreae** [comment]
Aha! It indeed wasn't the pagination, but the fact that `write` isn't guaranteed to successfully write all bytes from a buffer to a file :roll_eyes: 

Fixed here: https://github.com/p2panda/aquadoggo/pull/587
