### ISSUE TITLE
Are there any chances to merge multiple schemas' data together?

### ISSUE THREAD

**Issue by JasonkayZK** [p2panda/aquadoggo#590]
Hi there, i'm developing a local-first application recently, and i think p2panda can be a good choice.

But there is a problem here:

`Each devices will create it's own schema for storing data especially when it's offline during the first launch.`

So when the devices turned online, multiple schemas will be synced, such as `person_002030...`, `person_002031...`.

But they all had the same name `person` in all_schema_definition_v1.

So, i'm wondering if it could merge multiple schemas' data together for query? (Sorry for not very familiar with GraphQL)

**Comment by JasonkayZK** [comment]
Or i could name schema on my own so it could sync all data automatically? 😃

**Comment by adzialocha** [comment]
Hi @JasonkayZK!

> `Each devices will create it's own schema for storing data especially when it's offline during the first launch.`

Hui! Is this a sentence from us? That's indeed a bit confusing, we should improve that.

> So when the devices turned online, multiple schemas will be synced, such as `person_002030...`, `person_002031...`.
> 
> But they all had the same name `person` in all_schema_definition_v1.
> 
> So, i'm wondering if it could merge multiple schemas' data together for query? (Sorry for not very familiar with GraphQL)

If nodes want to collaborate on the same data they also need to use the same schemas (the hashes need to match). As soon as `aquadoggo` finds another node with the needed schemas it will pull them over and register them (it's a little bit like a database migration). If there's no other node like that (for example if you're offline) you can also deploy that schema manually on the node. We have a tool for this, check out https://github.com/p2panda/fishy - it's also handy for designing schemas in general.

**Comment by adzialocha** [comment]
> Or i could name schema on my own so it could sync all data automatically? 😃 

Exactly! So what you would do is:

1. Design a schema with `fishy`, best is maybe to follow the tutorial in the README https://github.com/p2panda/fishy#tutorial
2. Start an `aquadoggo` node
3. Deploy the schema on the node with `fishy deploy`

From this point on your node will support this schema and clients can start using it

**Comment by JasonkayZK** [comment]
Thanks for your explaination. ❤️ 

`fishy` seems worked as command line tool, but what i need is much more like a library so that it could do some migrations while the tauri app start. 😢

**Comment by JasonkayZK** [comment]
I figured it out! Once i kept the same key pair to create the schema, the schema id was exactly the same just as the `fishy` did!
But i think it might be a good idea to provide a library to do these stuffs just as the `fishy` do.

**Comment by JasonkayZK** [comment]
I saw this issue which is exactly what i want, thanks again for your amazing job!

https://github.com/p2panda/fishy/issues/3

**Comment by adzialocha** [comment]
> Thanks for your explaination. ❤️
> 
> `fishy` seems worked as command line tool, but what i need is much more like a library so that it could do some migrations while the tauri app start. 😢

We've implemented this logic in our Meli Android app here: https://github.com/p2panda/meli/blob/main/packages/app/lib/io/p2panda/schemas.dart#L40-L83 - it is fairly easy and can be implemented in our languages in case you need it for your app and you don't want to wait for `fishy` to support it programmatically. The logic is:

- Read `schema.lock` toml file
- Iterate over all `commits` in the file, publish `entry` and `operation` data as always with GraphQL API
- During every iteration step check if the entry already exists with `nextArgs`

**Comment by JasonkayZK** [comment]
> > Thanks for your explaination. ❤️
> > `fishy` seems worked as command line tool, but what i need is much more like a library so that it could do some migrations while the tauri app start. 😢
> 
> We've implemented this logic in our Meli Android app here: https://github.com/p2panda/meli/blob/main/packages/app/lib/io/p2panda/schemas.dart#L40-L83 - it is fairly easy and can be implemented in other languages in case you need it for your app and you don't want to wait for `fishy` to support it programmatically. The logic is:
> 
> * Read `schema.lock` toml file
> * Iterate over all `commits` in the file, publish `entry` and `operation` data as always with GraphQL API
> * During every iteration step check if the entry already exists with `nextArgs`

That's great, i'm working on it right now!

Thanks again for this cool protocol. 👍
