### ISSUE TITLE
allow_schema_ids config setting not working

### ISSUE THREAD

**Issue by jmanm** [p2panda/aquadoggo#602]
# Description 
I'm attempting to replicate a schema from one node to another and getting this log message:  "Replication failed: Incoming data could not be ingested: Schema is not supported".

## Steps to reproduce
1. Clone the repo
2. Edit ``config.toml`` to persist the database:
```toml
database_url = "sqlite:db/db.sqlite3"
```
3. Start the node:
```bash
cargo run -- -c ./config.toml --log-level info
```
4. Add a schema to the node. I used the mushroom-app-tutorial schema.
5. Add the resulting schema id(s) to ``config.toml``:
```toml
allow_schema_ids = [
    "schema_definition_v1",
    "schema_field_definition_v1",
    "blob_v1",
    "blob_piece_v1",
    "mushroom_<your document ID>",
    "mushroom_finding_<your document ID>"
]
```
6. Copy ``target/debug/aquadoggo`` and ``config.toml`` into a new folder.
7. In this folder, start a 2nd node:
```bash
./aquadoggo -c ./config.toml --log-level info
```

Node 1 will attempt to replicate the schema to node 2, but this error is logged:
``WARN  aquadoggo::replication::service] Replication failed: Incoming data could not be ingested: Schema is not supported``
and the schema is not replicated.

**Comment by adzialocha** [comment]
Thank you for raising this issue! This indeed looks like a logical bug.
