### ISSUE TITLE
Consider using `tokio` runtime

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#70]
This will make it easier for us to use crates like `qp2p` or QUIC related things in the future. There are currently no frameworks using `async_std` runtime for QUIC.

**Comment by adzialocha** [comment]
What do you think about this @sandreae and @cafca?

I think its good to look into this now as there is upcoming large refactorings around the API anyhow. The main reason of using the `async_std` runtime in the past was its simplicity but on the other hand we have problems integrating more "heavy-duty" crates since they all rely on the `tokio` runtime.

I'd be up for building on top of `tokio` now, which means removing `tide` and finding another framework for HTTP requests + GraphQL running on `tokio` and refactoring our async parts to comply with it as well. The code-base around async is fairly small currently so its a good chance to make the switch.

**Comment by sandreae** [comment]
I'm up for changing over to `tokio`. Maybe I'd like us to make a few more decisions about what which libs we want to use going forward with `aquadoggo` first though (like if we want to use `qp2p`). Otherwise we might change and then find we wanna use a sweet `async_std` lib ;-p

I see the benefit of changing now rather than later though :+1:

**Comment by adzialocha** [comment]
I had a go on it, the `tokio` switch was very easy (both runtimes almost follow the same async API now). We also don't need to change `async_graphql` as it is agnostic to the HTTP framework behind it.

The more important step was changing the HTTP framework. I've experimented with `axum` which felt nice so far (state / context handling didn't feel to verbose and intuitive API) but it seems to miss out on some nice testing features. Will investigate!
