### ISSUE TITLE
Dynamic GraphQL schema introspection

### ISSUE THREAD

**Issue by adzialocha** [p2panda/aquadoggo#72]

**Comment by cafca** [comment]
I think this should be closed by #141 and isn't closed already?

**Comment by adzialocha** [comment]
Yeah, thats true, but also mentioning here was a little redundant as with the new approach we get it "for free" without needing to "do" anything. So I thought its not really a "todo" anymore :-D

**Comment by adzialocha** [comment]
I had the feeling its a ticket which rather confuses us (what! WHAT DO I HAVE TO IMPLEMENT?!)

**Comment by cafca** [comment]
No problem :) It's just a quite distinct subtask within #141 so it kind of made sense to me to have it as a ticket.

**Comment by adzialocha** [comment]
> No problem :) It's just a quite distinct subtask within #141 so it kind of made sense to me to have it as a ticket.

Yeah, I get that as well! Feel free to reopen :+1:
