### ISSUE TITLE
Construct `Schema` from schema def & schema field def documents

### ISSUE THREAD

**Issue by sandreae** [p2panda/aquadoggo#78]
- check for dependencies if this is a system scheme with relations (`schema_definition_v1`)
  - if dependencies are met, move on
  - if dependencies aren't met... ??? send to our task queue (which doesn't exist yet)
- construct `Schema` from it's definition and fields, store in the DB

**Comment by sandreae** [comment]
stale...

**Comment by sandreae** [comment]
or maybe not....

**Comment by adzialocha** [comment]
Ah ja, right, that's different now .. I can imagine we could not have the service for now and remove the schema task?
